version: '3.7'
services: 
    api:
        container_name: 'go-location'
        build: '.'
        ports:
            - '8080:8080'
        depends_on: 
            - 'mongo'
            - 'redis'
        restart: 'always'
    redis:
        image: 'redis:latest'
        container_name: 'redis'
        ports:
            - '6379:6379'
    mongo:
        image: 'mongo:latest'
        container_name: 'mongo'
        ports:
            - '27017:27017'